### ISSUE TITLE
Unavailable entity_id shows js error

### ISSUE THREAD

**Issue by antontanderup** [antontanderup/mediocre-hass-media-player-cards#45]
Card should be guarded against this and show that the main player state is unavailable.

**Comment by pezzy-o** [comment]
I'm getting a similar error on the v0.20.0-alpha.0 Pre-Release. After I click on a search result, the searched item plays fine, but on the dashboard I get the following error messages which replace the card:
iPhone: undefined is not an object (evaluating 'I.startsWith')
Edge browser: Cannot read properties of undefined (reading 'startsWith')

The attributes of one of the affected media player entities are as follows:

```group_members: []
volume_level: 0.06
is_volume_muted: false
media_content_id: library://track/7740
media_content_type: music
media_duration: 269
media_position: 2
media_position_updated_at: "2025-05-05T10:01:41.814990+00:00"
media_title: Until It Sleeps
media_artist: Metallica
media_album_name: Load
media_album_artist: Metallica
app_id: music_assistant
shuffle: false
repeat: "off"
mass_player_type: player
active_queue: RINCON_F0F6C1A35F0C01400
device_class: speaker
entity_picture: >-
  /api/media_player_proxy/media_player.sonos_era_100?token=9d4640d01c3fbd0cfe6b0ac7e715e4e0a9ac0703a1c6f5615c2b6ed77c7d836c&cache=41ff8249c5af1e43
icon: mdi:speaker
friendly_name: Pezzy’s Office
supported_features: 4126271
```

**Comment by antontanderup** [comment]
Thank you for the info. It’s the missing source. Fix should be out next release.

**Comment by antontanderup** [comment]
Should be fixed in v0.20.0-beta.0 🫡

**Comment by pezzy-o** [comment]
Hmm I just tested after upgrading (and refreshing front end iOS app / CTRL+F5 refreshing Edge browser) and both error messages / behaviours described in my comment above are still present.

**Comment by pezzy-o** [comment]
I'm no JS master, but looking at the code (and doing a bit of searching), could it be that `!source.startsWith("media_player.")` is still being evaluated despite the addition of `!!source` because of the way that JS works?

If so, would this work?

```
const title =
  mediaTitle !== "" ? mediaTitle :
  typeof source === "string" && !source.startsWith("media_player.") ? source :
  friendlyName;
```

**Comment by antontanderup** [comment]
That would work yes. Super confused why !!undefined would be true, but I’ll do a typeof instead.
I think I’ll split that logic up a bit more too so it’s not a big shorthand string, now I’m at it.
I’ll try to have a look tonight.

**Comment by antontanderup** [comment]
Try out v0.20.0-beta.2
For what it's worth I could not reproduce the issue on v0.20.0-beta.0 with media players that had no source, so I think you might actually have had some caching issue.
In any event it was better to split up the logic a bit.

**Comment by pezzy-o** [comment]
The error is gone with v0.20.0-beta.2. Thanks Anton!
